name: Fetch new data & publish page

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm ci
    - run: export TWITTER_BEARER_TOKEN="${{ secrets.TWITTER_BEARER_TOKEN }}"
    - run: npm run fetch-new-data
    - run: npm run build
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        # Build directory to deploy
        build_dir: _site
        # Write the given domain name to the CNAME file
        fqdn: tweets.piraces.dev
        jekyll: false
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
